package io.github.colochampre.riskofrain_mobs.client.models;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import io.github.colochampre.riskofrain_mobs.RoRmod;
import io.github.colochampre.riskofrain_mobs.entities.StoneGolemEntity;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;

public class StoneGolemModel extends EntityModel<StoneGolemEntity> {
  public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(new ResourceLocation(RoRmod.MODID, "stone_golem_entity"), "main");
  protected final ModelPart Core;
  protected ModelPart Torso_axis;
  protected ModelPart Torso;
  protected ModelPart Torso_2;
  protected ModelPart Torso_3;
  protected ModelPart Torso_4;
  protected ModelPart Torso_5;
  protected ModelPart Torso_6;
  protected ModelPart Neck_axis;
  protected ModelPart Neck;
  protected ModelPart Head_axis;
  protected ModelPart Head;
  protected ModelPart Head_2;
  protected ModelPart Eye;
  protected ModelPart Head_3_1;
  protected ModelPart Head_3_2;
  protected ModelPart Head_4_1;
  protected ModelPart Head_5_1;
  protected ModelPart Head_4_2;
  protected ModelPart Head_5_2;
  protected ModelPart Head_6;
  protected ModelPart Head_7_1;
  protected ModelPart Head_7_2;
  protected ModelPart Head_7_3;
  protected ModelPart Head_8_1;
  protected ModelPart Head_8_2_1;
  protected ModelPart Head_8_2_2;
  protected ModelPart Left_shoulder_axis;
  protected ModelPart Left_shoulder;
  protected ModelPart Left_shoulder_2;
  protected ModelPart Left_shoulder_3;
  protected ModelPart Left_arm_1_axis;
  protected ModelPart Left_arm_1;
  protected ModelPart Left_arm_1_1;
  protected ModelPart Left_arm_2_axis;
  protected ModelPart Left_arm_2;
  protected ModelPart Left_forearm_axis;
  protected ModelPart Left_forearm;
  protected ModelPart Left_forearm_2;
  protected ModelPart Left_forearm_3;
  protected ModelPart Left_thumb;
  protected ModelPart Left_hand_1_axis;
  protected ModelPart Left_hand_1;
  protected ModelPart Left_hand_1_1;
  protected ModelPart Left_hand_2_axis;
  protected ModelPart Left_hand_2;
  protected ModelPart Left_hand_2_1;
  protected ModelPart Right_shoulder_axis;
  protected ModelPart Right_shoulder;
  protected ModelPart Right_arm_axis;
  protected ModelPart Right_arm;
  protected ModelPart Right_arm_2;
  protected ModelPart Right_arm_3;
  protected ModelPart Right_elbow_axis;
  protected ModelPart Right_elbow;
  protected ModelPart Right_forearm_axis;
  protected ModelPart Right_forearm;
  protected ModelPart Right_forearm_2;
  protected ModelPart Right_forearm_3;
  protected ModelPart Right_thumb;
  protected ModelPart Right_hand_1_axis;
  protected ModelPart Right_hand_1;
  protected ModelPart Right_hand_1_1;
  protected ModelPart Right_hand_2_axis;
  protected ModelPart Right_hand_2;
  protected ModelPart Right_hand_2_1;
  protected ModelPart Hip_axis;
  protected ModelPart Hip;
  protected ModelPart Hip_2;
  protected ModelPart Hip_3_1;
  protected ModelPart Hip_3_2;
  protected ModelPart Left_leg_axis;
  protected ModelPart Left_leg;
  protected ModelPart Left_leg_1_1;
  protected ModelPart Left_leg_1_2;
  protected ModelPart Left_leg_2_axis;
  protected ModelPart Left_leg_2;
  protected ModelPart Left_leg_2_1;
  protected ModelPart Left_leg_2_2;
  protected ModelPart Right_leg_axis;
  protected ModelPart Right_leg;
  protected ModelPart Right_leg_1_1;
  protected ModelPart Right_leg_1_2;
  protected ModelPart Right_leg_2_axis;
  protected ModelPart Right_leg_2;
  protected ModelPart Right_leg_2_1;
  protected ModelPart Right_leg_2_2;

  public StoneGolemModel(ModelPart root) {
    this.Core = root.getChild("Core");
    this.Torso_axis = Core.getChild("Torso_axis");
    this.Hip_axis = Core.getChild("Hip_axis");
    this.Torso = Torso_axis.getChild("Torso");
    this.Torso_2 = Torso.getChild("Torso_2");
    this.Torso_3 = Torso_2.getChild("Torso_3");
    this.Torso_4 = Torso_3.getChild("Torso_4");
    this.Torso_5 = Torso_4.getChild("Torso_5");
    this.Torso_6 = Torso_5.getChild("Torso_6");
    this.Neck_axis = Torso_5.getChild("Neck_axis");
    this.Left_shoulder_axis = Torso_5.getChild("Left_shoulder_axis");
    this.Right_shoulder_axis = Torso_5.getChild("Right_shoulder_axis");
    this.Neck = Neck_axis.getChild("Neck");
    this.Head_axis = Neck.getChild("Head_axis");
    this.Head = Head_axis.getChild("Head");
    this.Head_2 = Head.getChild("Head_2");
    this.Eye = Head_2.getChild("Eye");
    this.Head_3_1 = Head_2.getChild("Head_3_1");
    this.Head_3_2 = Head_2.getChild("Head_3_2");
    this.Head_4_1 = Head_3_1.getChild("Head_4_1");
    this.Head_4_2 = Head_3_2.getChild("Head_4_2");
    this.Head_5_1 = Head_4_1.getChild("Head_5_1");
    this.Head_5_2 = Head_4_2.getChild("Head_5_2");
    this.Head_6 = Head_5_2.getChild("Head_6");
    this.Head_7_1 = Head_6.getChild("Head_7_1");
    this.Head_7_2 = Head_6.getChild("Head_7_2");
    this.Head_7_3 = Head_6.getChild("Head_7_3");
    this.Head_8_1 = Head_7_3.getChild("Head_8_1");
    this.Head_8_2_1 = Head_7_3.getChild("Head_8_2_1");
    this.Head_8_2_2 = Head_8_2_1.getChild("Head_8_2_2");
    this.Left_shoulder = Left_shoulder_axis.getChild("Left_shoulder");
    this.Left_shoulder_2 = Left_shoulder.getChild("Left_shoulder_2");
    this.Left_shoulder_3 = Left_shoulder_2.getChild("Left_shoulder_3");
    this.Left_arm_1_axis = Left_shoulder_3.getChild("Left_arm_1_axis");
    this.Left_arm_1 = Left_arm_1_axis.getChild("Left_arm_1");
    this.Left_arm_1_1 = Left_arm_1.getChild("Left_arm_1_1");
    this.Left_arm_2_axis = Left_arm_1_1.getChild("Left_arm_2_axis");
    this.Left_arm_2 = Left_arm_2_axis.getChild("Left_arm_2");
    this.Left_forearm_axis = Left_arm_2.getChild("Left_forearm_axis");
    this.Left_forearm = Left_forearm_axis.getChild("Left_forearm");
    this.Left_forearm_2 = Left_forearm.getChild("Left_forearm_2");
    this.Left_forearm_3 = Left_forearm_2.getChild("Left_forearm_3");
    this.Left_thumb = Left_forearm_2.getChild("Left_thumb");
    this.Left_hand_1_axis = Left_forearm_3.getChild("Left_hand_1_axis");
    this.Left_hand_1 = Left_hand_1_axis.getChild("Left_hand_1");
    this.Left_hand_1_1 = Left_hand_1.getChild("Left_hand_1_1");
    this.Left_hand_2_axis = Left_hand_1_1.getChild("Left_hand_2_axis");
    this.Left_hand_2 = Left_hand_2_axis.getChild("Left_hand_2");
    this.Left_hand_2_1 = Left_hand_2.getChild("Left_hand_2_1");
    this.Right_shoulder = Right_shoulder_axis.getChild("Right_shoulder");
    this.Right_arm_axis = Right_shoulder.getChild("Right_arm_axis");
    this.Right_arm = Right_arm_axis.getChild("Right_arm");
    this.Right_arm_2 = Right_arm.getChild("Right_arm_2");
    this.Right_arm_3 = Right_arm_2.getChild("Right_arm_3");
    this.Right_elbow_axis = Right_arm_3.getChild("Right_elbow_axis");
    this.Right_elbow = Right_elbow_axis.getChild("Right_elbow");
    this.Right_forearm_axis = Right_elbow.getChild("Right_forearm_axis");
    this.Right_forearm = Right_forearm_axis.getChild("Right_forearm");
    this.Right_forearm_2 = Right_forearm.getChild("Right_forearm_2");
    this.Right_forearm_3 = Right_forearm_2.getChild("Right_forearm_3");
    this.Right_thumb = Right_forearm_2.getChild("Right_thumb");
    this.Right_hand_1_axis = Right_forearm_3.getChild("Right_hand_1_axis");
    this.Right_hand_1 = Right_hand_1_axis.getChild("Right_hand_1");
    this.Right_hand_1_1 = Right_hand_1.getChild("Right_hand_1_1");
    this.Right_hand_2_axis = Right_hand_1_1.getChild("Right_hand_2_axis");
    this.Right_hand_2 = Right_hand_2_axis.getChild("Right_hand_2");
    this.Right_hand_2_1 = Right_hand_2.getChild("Right_hand_2_1");
    this.Hip = Hip_axis.getChild("Hip");
    this.Left_leg_axis = Hip.getChild("Left_leg_axis");
    this.Right_leg_axis = Hip.getChild("Right_leg_axis");
    this.Hip_2 = Hip.getChild("Hip_2");
    this.Hip_3_1 = Hip_2.getChild("Hip_3_1");
    this.Hip_3_2 = Hip_2.getChild("Hip_3_2");
    this.Left_leg = Left_leg_axis.getChild("Left_leg");
    this.Left_leg_1_1 = Left_leg.getChild("Left_leg_1_1");
    this.Left_leg_1_2 = Left_leg_1_1.getChild("Left_leg_1_2");
    this.Left_leg_2_axis = Left_leg_1_2.getChild("Left_leg_2_axis");
    this.Left_leg_2 = Left_leg_2_axis.getChild("Left_leg_2");
    this.Left_leg_2_1 = Left_leg_2.getChild("Left_leg_2_1");
    this.Left_leg_2_2 = Left_leg_2_1.getChild("Left_leg_2_2");
    this.Right_leg = Right_leg_axis.getChild("Right_leg");
    this.Right_leg_1_1 = Right_leg.getChild("Right_leg_1_1");
    this.Right_leg_1_2 = Right_leg_1_1.getChild("Right_leg_1_2");
    this.Right_leg_2_axis = Right_leg_1_2.getChild("Right_leg_2_axis");
    this.Right_leg_2 = Right_leg_2_axis.getChild("Right_leg_2");
    this.Right_leg_2_1 = Right_leg_2.getChild("Right_leg_2_1");
    this.Right_leg_2_2 = Right_leg_2_1.getChild("Right_leg_2_2");
  }

  public static LayerDefinition createBodyLayer() {
    var mesh = new MeshDefinition();
    PartDefinition parts = mesh.getRoot();

    PartDefinition Core = parts.addOrReplaceChild("Core", CubeListBuilder.create().texOffs(1, 149).addBox(-5.0F, -1.5F, -2.5F, 10.0F, 2.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -8.5F, 0.0F));
    PartDefinition Torso_axis = Core.addOrReplaceChild("Torso_axis", CubeListBuilder.create().texOffs(32, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -2.5F, 0.0F));
    PartDefinition Torso = Torso_axis.addOrReplaceChild("Torso", CubeListBuilder.create().texOffs(1, 49).addBox(-12.5F, -0.5F, -3.5F, 25.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Torso_2 = Torso.addOrReplaceChild("Torso_2", CubeListBuilder.create().texOffs(66, 41).addBox(-13.5F, -8.0F, -4.0F, 27.0F, 8.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.5F, 0.0F));
    PartDefinition Torso_3 = Torso_2.addOrReplaceChild("Torso_3", CubeListBuilder.create().texOffs(137, 47).addBox(-12.5F, -2.0F, -4.0F, 25.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -8.0F, 0.0F));
    PartDefinition Torso_4 = Torso_3.addOrReplaceChild("Torso_4", CubeListBuilder.create().texOffs(204, 47).addBox(-12.5F, -3.0F, -4.0F, 24.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -1.0F, 0.0F));
    PartDefinition Torso_5 = Torso_4.addOrReplaceChild("Torso_5", CubeListBuilder.create().texOffs(269, 49).addBox(-11.5F, -2.0F, -3.5F, 22.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -2.0F, 0.0F));
    PartDefinition Torso_6 = Torso_5.addOrReplaceChild("Torso_6", CubeListBuilder.create().texOffs(328, 54).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(-9.5F, -2.0F, -2.5F));
    PartDefinition Neck_axis = Torso_5.addOrReplaceChild("Neck_axis", CubeListBuilder.create().texOffs(37, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.0F, -3.0F, 0.0F));
    PartDefinition Neck = Neck_axis.addOrReplaceChild("Neck", CubeListBuilder.create().texOffs(1, 35).addBox(-3.0F, -0.5F, -2.0F, 6.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Head_axis = Neck.addOrReplaceChild("Head_axis", CubeListBuilder.create().texOffs(42, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -2.0F, 0.0F));
    PartDefinition Head = Head_axis.addOrReplaceChild("Head", CubeListBuilder.create().texOffs(1, 26).addBox(-9.0F, -0.5F, -3.5F, 18.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Head_2 = Head.addOrReplaceChild("Head_2", CubeListBuilder.create().texOffs(52, 25).addBox(-11.0F, -1.5F, -4.0F, 22.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Head_3_1 = Head_2.addOrReplaceChild("Head_3_1", CubeListBuilder.create().texOffs(137, 15).addBox(-10.0F, -1.0F, -4.0F, 10.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(-2.0F, -1.5F, 0.0F));
    PartDefinition Head_3_2 = Head_2.addOrReplaceChild("Head_3_2", CubeListBuilder.create().texOffs(1, 15).addBox(0.0F, -1.0F, -4.0F, 10.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(2.0F, -1.5F, 0.0F));
    PartDefinition Head_4_1 = Head_3_1.addOrReplaceChild("Head_4_1", CubeListBuilder.create().texOffs(174, 12).addBox(-9.0F, -4.0F, -4.0F, 9.0F, 4.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(-1.0F, -1.0F, 0.0F));
    PartDefinition Head_4_2 = Head_3_2.addOrReplaceChild("Head_4_2", CubeListBuilder.create().texOffs(38, 12).addBox(0.0F, -4.0F, -4.0F, 9.0F, 4.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(1.0F, -1.0F, 0.0F));
    PartDefinition Head_5_1 = Head_4_1.addOrReplaceChild("Head_5_1", CubeListBuilder.create().texOffs(209, 15).addBox(-10.0F, -1.0F, -4.0F, 10.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(1.0F, -4.0F, 0.0F));
    PartDefinition Head_5_2 = Head_4_2.addOrReplaceChild("Head_5_2", CubeListBuilder.create().texOffs(73, 15).addBox(0.0F, -1.0F, -4.0F, 10.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(-1.0F, -4.0F, 0.0F));
    PartDefinition Head_6 = Head_5_2.addOrReplaceChild("Head_6", CubeListBuilder.create().texOffs(1, 1).addBox(-11.0F, -1.0F, -4.0F, 23.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(-2.0F, -1.0F, 0.0F));
    PartDefinition Head_7_1 = Head_6.addOrReplaceChild("Head_7_1", CubeListBuilder.create().texOffs(130, 4).addBox(-1.5F, -1.0F, -2.5F, 3.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(-8.5F, -1.0F, 1.5F));
    PartDefinition Head_7_2 = Head_6.addOrReplaceChild("Head_7_2", CubeListBuilder.create().texOffs(111, 2).addBox(-2.0F, -1.0F, -3.5F, 2.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-5.0F, -1.0F, 0.5F));
    PartDefinition Head_7_3 = Head_6.addOrReplaceChild("Head_7_3", CubeListBuilder.create().texOffs(64, 2).addBox(0.0F, -1.0F, -3.5F, 16.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-5.0F, -1.0F, 0.0F));
    PartDefinition Head_8_1 = Head_7_3.addOrReplaceChild("Head_8_1", CubeListBuilder.create().texOffs(173, 8).addBox(-1.0F, -1.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(7.0F, -1.0F, -3.0F));
    PartDefinition Head_8_2_1 = Head_7_3.addOrReplaceChild("Head_8_2_1", CubeListBuilder.create().texOffs(147, 5).addBox(-2.0F, -1.0F, -1.5F, 4.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offset(13.0F, -1.0F, -2.0F));
    PartDefinition Head_8_2_2 = Head_8_2_1.addOrReplaceChild("Head_8_2_2", CubeListBuilder.create().texOffs(164, 7).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -1.0F, 0.0F));
    PartDefinition Eye = Head_2.addOrReplaceChild("Eye", CubeListBuilder.create().texOffs(110, 11).addBox(-3.0F, -6.0F, -3.5F, 6.0F, 6.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -1.5F, 0.5F));
    PartDefinition Left_shoulder_axis = Torso_5.addOrReplaceChild("Left_shoulder_axis", CubeListBuilder.create().texOffs(47, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(16.5F, -1.5F, 0.0F));
    PartDefinition Left_shoulder = Left_shoulder_axis.addOrReplaceChild("Left_shoulder", CubeListBuilder.create().texOffs(1, 67).addBox(-2.5F, -0.5F, -2.5F, 5.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.5235988F));
    PartDefinition Left_shoulder_2 = Left_shoulder.addOrReplaceChild("Left_shoulder_2", CubeListBuilder.create().texOffs(23, 58).addBox(-4.0F, -1.0F, -4.0F, 8.0F, 7.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 1.5F, 0.0F));
    PartDefinition Left_shoulder_3 = Left_shoulder_2.addOrReplaceChild("Left_shoulder_3", CubeListBuilder.create().texOffs(56, 66).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Left_arm_1_axis = Left_shoulder_3.addOrReplaceChild("Left_arm_1_axis", CubeListBuilder.create().texOffs(52, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.0F, 9.0F, 0.0F, 0.0F, 0.0F, 0.5235988F));
    PartDefinition Left_arm_1 = Left_arm_1_axis.addOrReplaceChild("Left_arm_1", CubeListBuilder.create().texOffs(81, 68).addBox(-3.0F, -0.5F, -2.0F, 6.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, -0.08726646F, -0.2617994F));
    PartDefinition Left_arm_1_1 = Left_arm_1.addOrReplaceChild("Left_arm_1_1", CubeListBuilder.create().texOffs(102, 67).addBox(-3.5F, 0.0F, -2.5F, 7.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.5F, 0.0F));
    PartDefinition Left_arm_2_axis = Left_arm_1_1.addOrReplaceChild("Left_arm_2_axis", CubeListBuilder.create().texOffs(57, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 2.5F, 0.0F, 0.0F, 0.0F, 0.2617994F));
    PartDefinition Left_arm_2 = Left_arm_2_axis.addOrReplaceChild("Left_arm_2", CubeListBuilder.create().texOffs(127, 67).addBox(-4.5F, -0.5F, -2.0F, 9.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -0.5F, 0.0F, 0.0F, -0.08726646F));
    PartDefinition Left_forearm_axis = Left_arm_2.addOrReplaceChild("Left_forearm_axis", CubeListBuilder.create().texOffs(62, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 3.5F, 0.0F, 0.0F, 0.0F, 0.08726646F));
    PartDefinition Left_forearm = Left_forearm_axis.addOrReplaceChild("Left_forearm", CubeListBuilder.create().texOffs(1, 87).addBox(-3.0F, -0.5F, -4.0F, 6.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 0.0F, -1.0F, 0.0F, -0.08726646F, 0.0F));
    PartDefinition Left_forearm_2 = Left_forearm.addOrReplaceChild("Left_forearm_2", CubeListBuilder.create().texOffs(30, 74).addBox(-4.0F, 0.0F, -5.0F, 8.0F, 12.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.5F, 0.5F));
    PartDefinition Left_forearm_3 = Left_forearm_2.addOrReplaceChild("Left_forearm_3", CubeListBuilder.create().texOffs(67, 87).addBox(-3.0F, 0.0F, -4.0F, 6.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 12.0F, -0.5F));
    PartDefinition Left_hand_1_axis = Left_forearm_3.addOrReplaceChild("Left_hand_1_axis", CubeListBuilder.create().texOffs(67, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 2.0F, 0.5F));
    PartDefinition Left_hand_1 = Left_hand_1_axis.addOrReplaceChild("Left_hand_1", CubeListBuilder.create().texOffs(96, 88).addBox(-2.5F, -0.5F, -3.5F, 5.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, -0.5F));
    PartDefinition Left_hand_1_1 = Left_hand_1.addOrReplaceChild("Left_hand_1_1", CubeListBuilder.create().texOffs(121, 88).addBox(-2.0F, 0.5F, -3.5F, 4.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.0F, 0.0F));
    PartDefinition Left_hand_2_axis = Left_hand_1_1.addOrReplaceChild("Left_hand_2_axis", CubeListBuilder.create().texOffs(72, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(1.0F, 2.5F, 0.0F));
    PartDefinition Left_hand_2 = Left_hand_2_axis.addOrReplaceChild("Left_hand_2", CubeListBuilder.create().texOffs(144, 86).addBox(-2.5F, -0.5F, -3.5F, 5.0F, 3.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-1.0F, 0.0F, 0.0F));
    PartDefinition Left_hand_2_1 = Left_hand_2.addOrReplaceChild("Left_hand_2_1", CubeListBuilder.create().texOffs(169, 88).addBox(-2.0F, 0.0F, -3.0F, 4.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 2.5F, 0.0F));
    PartDefinition Left_thumb = Left_forearm_2.addOrReplaceChild("Left_thumb", CubeListBuilder.create().texOffs(190, 88).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offset(-2.0F, 6.5F, -6.0F));
    PartDefinition Right_shoulder_axis = Torso_5.addOrReplaceChild("Right_shoulder_axis", CubeListBuilder.create().texOffs(77, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-15.5F, 0.0F, 0.0F));
    PartDefinition Right_shoulder = Right_shoulder_axis.addOrReplaceChild("Right_shoulder", CubeListBuilder.create().texOffs(154, 59).addBox(-3.0F, -0.5F, -6.0F, 6.0F, 2.0F, 12.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.5F, 0.0F, 0.0F, 0.7853982F));
    PartDefinition Right_arm_axis = Right_shoulder.addOrReplaceChild("Right_arm_axis", CubeListBuilder.create().texOffs(82, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 4.0F, 0.0F, 0.0F, 0.0F, -0.7853982F));
    PartDefinition Right_arm = Right_arm_axis.addOrReplaceChild("Right_arm", CubeListBuilder.create().texOffs(191, 67).addBox(-2.5F, -0.5F, -2.5F, 5.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.08726646F, 0.3926991F));
    PartDefinition Right_arm_2 = Right_arm.addOrReplaceChild("Right_arm_2", CubeListBuilder.create().texOffs(212, 58).addBox(-4.0F, -1.0F, -4.0F, 8.0F, 7.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 1.5F, 0.0F));
    PartDefinition Right_arm_3 = Right_arm_2.addOrReplaceChild("Right_arm_3", CubeListBuilder.create().texOffs(245, 66).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Right_elbow_axis = Right_arm_3.addOrReplaceChild("Right_elbow_axis", CubeListBuilder.create().texOffs(87, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.5F, 9.0F, 0.0F, 0.0F, 0.0F, -0.3926991F));
    PartDefinition Right_elbow = Right_elbow_axis.addOrReplaceChild("Right_elbow", CubeListBuilder.create().texOffs(203, 91).addBox(-2.0F, -0.5F, -2.0F, 4.0F, 1.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));
    PartDefinition Right_forearm_axis = Right_elbow.addOrReplaceChild("Right_forearm_axis", CubeListBuilder.create().texOffs(92, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 2.0F, 0.0F));
    PartDefinition Right_forearm = Right_forearm_axis.addOrReplaceChild("Right_forearm", CubeListBuilder.create().texOffs(220, 87).addBox(-3.0F, -0.5F, -4.0F, 6.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 0.0F, -1.0F, 0.0F, 0.08726646F, 0.0F));
    PartDefinition Right_forearm_2 = Right_forearm.addOrReplaceChild("Right_forearm_2", CubeListBuilder.create().texOffs(249, 74).addBox(-4.0F, 0.0F, -5.0F, 8.0F, 12.0F, 10.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.5F, 0.5F));
    PartDefinition Right_forearm_3 = Right_forearm_2.addOrReplaceChild("Right_forearm_3", CubeListBuilder.create().texOffs(286, 87).addBox(-3.0F, 0.0F, -4.0F, 6.0F, 1.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 12.0F, -0.5F));
    PartDefinition Right_hand_1_axis = Right_forearm_3.addOrReplaceChild("Right_hand_1_axis", CubeListBuilder.create().texOffs(97, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 2.0F, 0.5F));
    PartDefinition Right_hand_1 = Right_hand_1_axis.addOrReplaceChild("Right_hand_1", CubeListBuilder.create().texOffs(315, 88).addBox(-2.5F, -0.5F, -3.5F, 5.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, -0.5F));
    PartDefinition Right_hand_1_1 = Right_hand_1.addOrReplaceChild("Right_hand_1_1", CubeListBuilder.create().texOffs(340, 88).addBox(-2.0F, 0.5F, -3.5F, 4.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 0.0F, 0.0F));
    PartDefinition Right_hand_2_axis = Right_hand_1_1.addOrReplaceChild("Right_hand_2_axis", CubeListBuilder.create().texOffs(102, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 2.5F, 0.0F));
    PartDefinition Right_hand_2 = Right_hand_2_axis.addOrReplaceChild("Right_hand_2", CubeListBuilder.create().texOffs(363, 86).addBox(-2.5F, -0.5F, -3.5F, 5.0F, 3.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 0.0F, 0.0F));
    PartDefinition Right_hand_2_1 = Right_hand_2.addOrReplaceChild("Right_hand_2_1", CubeListBuilder.create().texOffs(388, 88).addBox(-2.0F, 0.0F, -3.0F, 4.0F, 2.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 2.5F, 0.0F));
    PartDefinition Right_thumb = Right_forearm_2.addOrReplaceChild("Right_thumb", CubeListBuilder.create().texOffs(409, 88).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offset(2.0F, 6.5F, -6.0F));
    PartDefinition Hip_axis = Core.addOrReplaceChild("Hip_axis", CubeListBuilder.create().texOffs(107, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 1.5F, 0.0F));
    PartDefinition Hip = Hip_axis.addOrReplaceChild("Hip", CubeListBuilder.create().texOffs(1, 97).addBox(-11.0F, -2.5F, -3.0F, 22.0F, 4.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 2.0F, 0.0F));
    PartDefinition Hip_2 = Hip.addOrReplaceChild("Hip_2", CubeListBuilder.create().texOffs(58, 101).addBox(-5.0F, 0.0F, -2.5F, 10.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 1.5F, 0.0F));
    PartDefinition Hip_3_1 = Hip_2.addOrReplaceChild("Hip_3_1", CubeListBuilder.create().texOffs(110, 101).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(-8.0F, -5.0F, 0.0F));
    PartDefinition Hip_3_2 = Hip_2.addOrReplaceChild("Hip_3_2", CubeListBuilder.create().texOffs(89, 101).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 1.0F, 5.0F, new CubeDeformation(0.0F)), PartPose.offset(8.0F, -5.0F, 0.0F));
    PartDefinition Left_leg_axis = Hip.addOrReplaceChild("Left_leg_axis", CubeListBuilder.create().texOffs(112, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(9.0F, 3.0F, 0.0F));
    PartDefinition Left_leg = Left_leg_axis.addOrReplaceChild("Left_leg", CubeListBuilder.create().texOffs(1, 121).addBox(-3.0F, -0.5F, -3.0F, 6.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, -0.17453292F, 0.0F));
    PartDefinition Left_leg_1_1 = Left_leg.addOrReplaceChild("Left_leg_1_1", CubeListBuilder.create().texOffs(26, 109).addBox(-4.5F, 0.0F, -4.5F, 8.0F, 11.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.5F, 0.5F));
    PartDefinition Left_leg_1_2 = Left_leg_1_1.addOrReplaceChild("Left_leg_1_2", CubeListBuilder.create().texOffs(59, 120).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 1.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 11.0F, -0.5F));
    PartDefinition Left_leg_2_axis = Left_leg_1_2.addOrReplaceChild("Left_leg_2_axis", CubeListBuilder.create().texOffs(117, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 2.0F, 0.0F));
    PartDefinition Left_leg_2 = Left_leg_2_axis.addOrReplaceChild("Left_leg_2", CubeListBuilder.create().texOffs(1, 141).addBox(-2.5F, -0.5F, -3.0F, 5.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -1.0F, 0.0F, -0.08726646F, 0.0F));
    PartDefinition Left_leg_2_1 = Left_leg_2.addOrReplaceChild("Left_leg_2_1", CubeListBuilder.create().texOffs(24, 129).addBox(-3.5F, 0.0F, -4.5F, 7.0F, 10.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.5F, 1.0F));
    PartDefinition Left_leg_2_2 = Left_leg_2_1.addOrReplaceChild("Left_leg_2_2", CubeListBuilder.create().texOffs(57, 139).addBox(-3.5F, 0.0F, -3.5F, 5.0F, 2.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(1.0F, 10.0F, 0.0F));
    PartDefinition Right_leg_axis = Hip.addOrReplaceChild("Right_leg_axis", CubeListBuilder.create().texOffs(122, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-10.0F, 3.0F, 0.0F));
    PartDefinition Right_leg = Right_leg_axis.addOrReplaceChild("Right_leg", CubeListBuilder.create().texOffs(88, 121).addBox(-3.0F, -0.5F, -3.0F, 7.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.17453292F, 0.0F));
    PartDefinition Right_leg_1_1 = Right_leg.addOrReplaceChild("Right_leg_1_1", CubeListBuilder.create().texOffs(115, 108).addBox(-4.5F, 0.0F, -4.0F, 9.0F, 12.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 0.5F, 0.0F));
    PartDefinition Right_leg_1_2 = Right_leg_1_1.addOrReplaceChild("Right_leg_1_2", CubeListBuilder.create().texOffs(150, 121).addBox(-3.5F, 0.0F, -3.0F, 7.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 12.0F, 0.0F));
    PartDefinition Right_leg_2_axis = Right_leg_1_2.addOrReplaceChild("Right_leg_2_axis", CubeListBuilder.create().texOffs(127, 154).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, 2.0F, 0.0F));
    PartDefinition Right_leg_2 = Right_leg_2_axis.addOrReplaceChild("Right_leg_2", CubeListBuilder.create().texOffs(82, 141).addBox(-2.5F, -0.5F, -3.0F, 5.0F, 1.0F, 6.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 1.0F, 0.0F, 0.08726646F, 0.0F));
    PartDefinition Right_leg_2_1 = Right_leg_2.addOrReplaceChild("Right_leg_2_1", CubeListBuilder.create().texOffs(105, 130).addBox(-3.5F, 0.0F, -4.5F, 7.0F, 9.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.5F, -0.5F));
    PartDefinition Right_leg_2_2 = Right_leg_2_1.addOrReplaceChild("Right_leg_2_2", CubeListBuilder.create().texOffs(138, 139).addBox(-3.5F, 0.0F, -3.5F, 5.0F, 2.0F, 7.0F, new CubeDeformation(0.0F)), PartPose.offset(1.0F, 9.0F, 0.0F));

    return LayerDefinition.create(mesh, 422, 157);
  }

  @Override
  public void renderToBuffer(PoseStack poseStack, VertexConsumer vertexConsumer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
    Core.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
  }

  @Override
  public void setupAnim(StoneGolemEntity entity, float limbSwing, float limbSwingAmmount, float ageInTicks, float headYaw, float headPitch) {

  }
}
