org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21
minecraft_version_range=[1.21,1.21)
forge_version=51.0.0
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21

mod_id=riskofrain_items
mod_name=Risk of Rain Items
mod_license=MIT
mod_version=1.1.0
mod_group_id=io.github.colochampre.riskofrain_items
mod_authors=Colo Champre
mod_description=This mod brings some content from the Risk of Rain universe into Minecraft!