org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)

forge_version=50.1.51
forge_version_range=[50,)
loader_version_range=[50,)
mapping_channel=official
mapping_version=1.20.6

mod_id=riskofrain_mobs
mod_name=Risk of Rain Mobs
mod_license=MIT
mod_version=1.2.2
mod_group_id=io.github.colochampre.riskofrain_mobs
mod_authors=Colo Champre
mod_description=This mod brings content from the Risk of Rain universe into Minecraft!